name: Build and Push Docker Images to DigitalOcean

on:
  push:
    branches:
      - master

jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Step 1: Get your code from GitHub
      - name: Checkout repository
        uses: actions/checkout@v4

      # Step 2: Login to DigitalOcean Container Registry
      - name: Login to DigitalOcean Registry
        uses: docker/login-action@v3
        with:
          registry: registry.digitalocean.com/housing-registry
          username: oauth2
          password: ${{ secrets.DO_TOKEN }}

      # Step 3: Build & push FastAPI image
      - name: Build and push FastAPI image
        run: |
          docker build -t registry.digitalocean.com/housing-registry/housing-api:latest ./api
          docker push registry.digitalocean.com/housing-registry/housing-api:latest

      # Step 4: Build & push Streamlit image
      - name: Build and push Streamlit image
        run: |
          docker build -t registry.digitalocean.com/housing-registry/housing-streamlit:latest ./streamlit
          docker push registry.digitalocean.com/housing-registry/housing-streamlit:latest
